### ISSUE TITLE
No dll file

### ISSUE THREAD

**Issue by philipbower122** [wooferzfg/LiveSplit.TimerPause#1]
dll file is needed

**Comment by wooferzfg** [comment]
Can you be more specific?

**Comment by philipbower122** [comment]
everything is there its just needs to have a compiled .dll file so I can use it in LiveSplit. the dll means it will show up in the layout settings when i add a component

**Comment by wooferzfg** [comment]
https://github.com/wooferzfg/LiveSplit.TimerPause/releases/download/1.0/LiveSplit.TimerPause.dll

**Comment by philipbower122** [comment]
ok great thanks
